import type { Metadata } from "next";
import "./globals.css";
import { Raleway as FontSans } from "next/font/google"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="block space-y-6 p-10 pb-16">
          <div className="space-y-0.5">
            <h2 className="text-2xl font-bold tracking-tight">Volleyball Animation</h2>
            <p className="text-muted-foreground">
              Animation for each volleyball turn
            </p>
          </div>
          <Separator className="my-6" />
          <div className="flex w-full justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
